### ISSUE TITLE
remove surface quality rendering from Z14

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#156]
Too small to be properly distinguish, and would help speed rendering.

**Comment by Florimondable** [comment]
may be from z13 only

**Comment by Phyks** [comment]
Done in https://github.com/cyclosm/cyclosm-cartocss-style/commit/61e59fb0ec9f91e438ed04c2522bb03d16955560

**Comment by Florimondable** [comment]
@Phyks you forgot my last comment, I was not sure, I think we can have surface on Z14, with better rendering, OSM-fr tracks tracktype looks good at that zoom.
Don't revert but the ticket can stay open

**Comment by Phyks** [comment]
I quickly checked the rendered tiles and I was thinking surface at Z14 would be difficult to see. Let's keep this one open and see later if we can improve the rendering.
