### ISSUE TITLE
highway=pedestrian should have a specific style

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#67]
At the moment, `highway=pedestrian` is rendered as a regular way. The different style is only there for `path`/`footway`. We should probably have some different color or style for `highway=pedestrian`.

Typical source of example is around "Porte de Vanves": https://www.openstreetmap.org/#map=18/48.82731/2.30502 (blue-ish streets in default osm.org render).

**Comment by Phyks** [comment]
Pedestrian should probably be considered as having maxspeed of 20 for instance.

**Comment by Florimondable** [comment]
I consider to render Pedestrian in cyan close to green as maxspeed < 10km/h and very pedestrian friendly.

**Comment by Phyks** [comment]
Fixed in https://github.com/cyclosm/cyclosm-cartocss-style/pull/72/ I think.

**Comment by Florimondable** [comment]
No, not fixed, pedestrian is a road (a street) not a path, and should be render as it.

**Comment by Phyks** [comment]
This was fixed in #76.

Only remaining issue is that we are not applying the same style to areas. Typically https://www.openstreetmap.org/way/662601834#map=18/48.82713/2.30270 which is rendered in white here https://tiles.phyks.me/#18/48.82714/2.30435. Not sure what should be done here, it would mean the main squares would be rendered in green as well (https://tiles.phyks.me/#18/48.81903/2.31946 or https://tiles.phyks.me/#18/45.77643/3.08155 for instance).
