### ISSUE TITLE
Bug Report: highway=road Rendering Issue

### ISSUE THREAD

**Issue by cmoffroad** [cyclosm/cyclosm-cartocss-style#686]
### Description

I would like to bring to your attention an important issue regarding your rendering of unknown roads (highway=road).

<img width="179" alt="Screen Shot 2567-07-29 at 12 41 09" src="https://github.com/user-attachments/assets/e1409ab4-f25e-4213-b2a2-8c4cd76a9d38">

According to the OpenStreetMap wiki, the tag highway=road is intended for temporary use for roads/paths that have not yet been surveyed.

This can encompass a wide range of paths, from hiking trails to major motorways.

When a particular renderer needs to display these roads, it is advisable to make them visually distinct from other rendered ways to avoid confusion.

<img width="573" alt="Screen Shot 2567-07-20 at 16 49 30" src="https://github.com/user-attachments/assets/86d70407-3d50-4a62-b928-1b1a57a2220c">

For an outdoor-focused renderer like yours, there is no necessity to display highway=road tags. Displaying these unsurveyed or potentially erroneous roads and trails could mislead end-users.

For reference, Komoot, LocusMap, maps.me and now Strava, have already implemented solutions to hide these tags by default. We recommend adopting a similar approach to enhance the accuracy and reliability of your maps.

Sources:

- https://wiki.openstreetmap.org/wiki/Tag:highway%3Droad
- https://community.openstreetmap.org/t/new-lifecycle-tag-unconfirmed-highway/116102/26

### Steps to reproduce

1. Open the Overpass Query using this link: https://overpass-turbo.eu/s/1OIG 
2. Zoom out to your area of interest and click "Run." 
3. Zoom in on each `highway=road` segment from the results. 
4. Copy the zoom level and coordinates, then apply them to the Strava Map URL.
5. The `highway=road` segments appear as minor paved roads. 
6. These segments should not be visible until an OSM mapper surveys and classifies or removes them.

Sample:
- Open this OSM Way for reference: https://www.openstreetmap.org/way/89185730/history 
- Navigate to this segment at zoom 16, coordinates: 18.2289, 98.6966

**Comment by Phyks** [comment]
Hi!

Thanks a lot for the complete bug report, I've just pushed a commit to suppress `highway=road` render. It will be live on the map at next version/deployment.

Best

**Comment by cmoffroad** [comment]
Hi! When is the next version or deployment scheduled? It’s been 6 weeks since your last commit, but I haven’t seen any updates on the web tiles: https://b.tile-cyclosm.openstreetmap.fr/cyclosm/18/203406/117139.png

**Comment by Phyks** [comment]
I've deployed a new version (0.7.1) with this change.

**Comment by julcnx** [comment]
> I 've deployed a new version (0.7.1) with this change.

Cool, can you explain why the tile below still show the highway=road segment (bottom right corner, thick/short segment) ? I tried to clear cache but I don't see any difference. 
https://b.tile-cyclosm.openstreetmap.fr/cyclosm/18/203406/117139.png

**Comment by Phyks** [comment]
There is quite a lot of caching taking place across the infra. Therefore the changes will not be visible immediately. They will be visible once the caches expire, as tiles get updates in the underlying OSM objects.
